---
title: "data-sources"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data-sources}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(conmat)
```

NOTE - these data sources will get cleaned up before submission to CRAN. These data are still being cleaned and processed, but their current forms are shown below:

### eyre_transmission_probabilities

```{r eyre-transmission-probabilities}
eyre_transmission_probabilities

library(ggplot2)
library(stringr)
library(dplyr)
eyre_transmission_probabilities %>%
   group_by(
     setting,
     case_age_5y,
     contact_age_5y
   ) %>%
   summarise(
     across(
       probability,
       mean
     ),
     .groups = "drop"
   ) %>%
   rename(
     case_age = case_age_5y,
     contact_age = contact_age_5y
   ) %>%
   mutate(
     across(
       ends_with("age"),
       ~ factor(.x,
                levels = str_sort(
                  unique(.x),
                  numeric = TRUE
                )
       )
     )
   ) %>%
   ggplot(
     aes(
       x = case_age,
       y = contact_age,
       fill = probability
     )
   ) +
   facet_wrap(~setting) +
   geom_tile() +
   scale_fill_viridis_c() +
   coord_fixed() +
   theme_minimal() +
   theme(
     axis.text = element_text(angle = 45, hjust = 1)
   )

```


### abs_education_state

```{r abs-education-state}
abs_education_state
```

### abs_education_state_2020

```{r abs-education-state-2020}
abs_education_state_2020
```


### abs_employ_age_lga

```{r abs-employ-age-lga}
abs_employ_age_lga
```


### abs_household_lga

```{r abs-household-lga}
abs_household_lga
```


### abs_pop_age_lga_2016

```{r abs-pop-age-lga-2016}
abs_pop_age_lga_2016
```


### abs_pop_age_lga_2020

```{r abs-pop-age-lga-2020}
abs_pop_age_lga_2020
```


### abs_state_age

```{r abs-state-age}
abs_state_age
```
