---
title: "getting-started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{getting-started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(conmat)
library(socialmixr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(mgcv)
library(patchwork)
library(future)
plan(multisession, workers = 4)
```

```{r}
# build synthetic age-structured contact matrices with GAMs
# analysis of polymod data
# get polymod population for later use
polymod_population <- get_polymod_population()
polymod_population
```


```{r}
# fit a single overall contact model to polymod
example_contact_data_all <- get_polymod_contact_data("all") %>% 
  filter(age_from <= 10,
         age_to <= 10)


m_all <- fit_single_contact_model(
  contact_data = example_contact_data_all,
  population = polymod_population
)

m_all
```


```{r}
# predict contacts at 1y and 5y resolutions for inspection
# set age breaks
age_breaks_5y <- c(seq(0, 75, by = 5), Inf)

synthetic_all_5y <- predict_contacts(
  model = m_all, 
  population = polymod_population,
  age_breaks = age_breaks_5y
) %>%
  predictions_to_matrix()

synthetic_all_5y
```


```{r}
age_breaks_1y <- c(seq(0, 100, by = 1), Inf)

age_breaks_1y

synthetic_all_1y <- predict_contacts(
  model = m_all, 
  population = polymod_population,
  age_breaks = age_breaks_1y
) %>%
  predictions_to_matrix()

synthetic_all_1y
```


```{r}
# compute setting-specific and combined age matrices for polymod
synthetic_settings_5y_polymod <- extrapolate_polymod(
  population = polymod_population
)

synthetic_settings_5y_polymod
```

```{r}
synthetic_settings_5y_sydney <- extrapolate_polymod(
  population = abs_age_lga("Sydney (C)")
)
synthetic_settings_5y_sydney

```

```{r}
# extrapolate to other contexts
synthetic_settings_5y_italy_2005 <- extrapolate_polymod(
  population = wpp_age("Italy", "2005")
)
synthetic_settings_5y_italy_2005
```

```{r}
# empirical 5y polymod matrix
empirical_all_5y <- contact_matrix(
  survey = polymod,
  age.limits = seq(0, 75, by = 5),
  symmetric = FALSE,
  split = FALSE,
  missing.participant.age = "remove",
  missing.contact.age = "remove"
)$matrix

empirical_all_5y
# plot setting-specific matrices
```


```{r}
# synthetic_setting_specific_polymod.png
plot_setting_matrices(synthetic_settings_5y_polymod)
```


```{r}
# synthetic_setting_specific_italy.png
plot_setting_matrices(
  synthetic_settings_5y_italy_2005,
  title = "Setting-specific synthetic contact matrices (Italy 2005 projected)"
)
```


```{r}
# empirical_vs_synthetic.png
# plot empirical vs synthetic matrices
plot_matrix(empirical_all_5y) +
  ggtitle("empirical (socialmixr)") +
  plot_matrix(synthetic_settings_5y_polymod$all) +
  ggtitle("synthetic by setting, combined") +
  plot_matrix(synthetic_all_5y) +
  ggtitle("synthetic all at once") +
  plot_matrix(synthetic_all_1y) +
  ggtitle("synthetic all at once (1y)") +
  theme(axis.text = element_blank()) +
  plot_layout(ncol = 2) +
  plot_annotation(
    title = "Empirical vs synthetic matrices (all polymod data)"
  )
```


```{r}
# polymod_raw_settings.png
# visualise empirical contact rate estimates
bind_rows(
  home = get_polymod_contact_data("home"),
  school = get_polymod_contact_data("school"),
  work = get_polymod_contact_data("work"),
  other = get_polymod_contact_data("other"),
  .id = "setting"
) %>%
  mutate(
    rate = contacts / participants,
    setting = factor(
      setting,
      levels = c(
        "home", "school", "work", "other"
      )
    )
  ) %>%
  group_by(
    setting
  ) %>%
  mutate(
    `relative contact rate` = rate / max(rate)
  ) %>%
  ungroup() %>%
  ggplot(
    aes(
      x = age_from,
      y = age_to,
      fill = `relative contact rate`
    )
  ) +
  facet_wrap(
    ~ setting,
    ncol = 2,
    scales = "free"
  ) +
  geom_tile() +
  scale_fill_distiller(
    direction = 1,
    trans = "sqrt"
  ) +
  theme_minimal()
```

